### PR TITLE
Upgrade to Mahout 0.10.0 #54

### PR DESCRIPTION
**Pull request by lewismc**
@jnioche you were right on this one.
I've noticed that Hadoop API shows up as being deprecated now so this patch, if and once merged could do with some extensive testing.
I'm dockerizing Behemoth with Hadoop 1.2.1 and Mahout 0.10.0 right now so hopefully any issues will come out from that.

### CODE REVIEW

**Comment by jnioche** [comment]
Not sure what I'm right about but it's always a relief to hear ;-)

> I'm dockerizing Behemoth with Hadoop 1.2.1 and Mahout 0.10.0 right now so hopefully any issues will come out from that.

Interesting. Let me know how your tests went and I'll merge if OK

**Comment by lewismc** [comment]
Will do Julien thanks. I'll follow up in due course.


On Friday, May 15, 2015, Julien Nioche <notifications@github.com> wrote:

> Not sure what I'm right about but it's always a relief to hear ;-)
>
> I'm dockerizing Behemoth with Hadoop 1.2.1 and Mahout 0.10.0 right now so
> hopefully any issues will come out from that.
>
> Interesting. Let me know how your tests went and I'll merge if OK
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DigitalPebble/behemoth/pull/55#issuecomment-102311601>
> .
>


-- 
*Lewis*

**Comment by jnioche** [comment]
@lewismc it's been a while. Shall we close this one? Mahout's pretty dead now anyway and Azazello will allow closer integration with Spark's MLib. What do you think?

**Comment by lewismc** [comment]
@jnioche yes I would say that you could probably close this off if you want.

**Comment by jnioche** [comment]
@lewismc Having said that it would also be ok to upgrade if this causes no trouble. Do you remember having any issues when upgrading Mahout?

BTW how's everything? still at Nasa?

**Comment by lewismc** [comment]
bq. Do you remember having any issues when upgrading Mahout?
No, I had no issues but this was a while ago and I also saw that Mahout 1.12.0 has been released recently. For the time being I think that this issue can most likely be left and/or closed.

bq. BTW how's everything? still at Nasa? 
Yes I am. Things are going well Julien thanks for asking. It's all about work and life balance... keeping everything in perspective and trying to keep a balance is what i am trying to achieve right now Julien. :)

**Pull request closed without merging**
